# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Awesome Project Landing Page
email: edward@syllogism.xyz
author: Edward Shen
description: >- # this means to ignore newlines until "baseurl:"
  This is a landing page template for my projects. It attempts to be thin yet flexible.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://syllogism.xyz" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: edward-shen

# Build settings
markdown: kramdown
# plugins:
#  - jekyll-feed
syntax_highlighter: rouge

permalink: :title/

kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

repository: edward-shen/awesome-project-homepage

plugins:
  - "jekyll-github-metadata"

defaults:
  -
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - README.md